name: pytorch_sac
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip:
    - termcolor
    - git+https://github.com/deepmind/dm_control.git
    - git+https://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra.git@0.11_branch
